name: Build MicroPython for PICO

permissions:
  contents: write  # Permitir escritura en el contenido del repositorio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone lv_micropython repository
      run: |
        git clone --recurse-submodules https://github.com/lvgl/lv_micropython.git
        cd lv_micropython
        git submodule update --init --recursive lib/lv_bindings

    - name: Build mpy-cross
      run: |
        cd lv_micropython
        make -C mpy-cross

    - name: Initialize Micropython submodules
      run: |
        cd lv_micropython
        make -C ports/rp2 BOARD=PICO submodules

    - name: Build PICO port
      run: |
        cd lv_micropython
        make -j -C ports/rp2 BOARD=PICO USER_C_MODULES=../../lib/lv_bindings/bindings.cmake
        mkdir -p ./artifacts
        cp ports/rp2/build-PICO/firmware.uf2 ./artifacts/PICO.uf2  # Mover el archivo UF2

    - name: Generate Tag
      id: tag
      run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ env.TAG_NAME }} 
        title: "MicroPython + LVGL Display Driver Release for version ${{ env.TAG_NAME }}"
        files: ./artifacts/PICO.uf2  # Especificar correctamente el archivo UF2
